python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCMilestone/CDCMilestone-allBND-hq.vcf > run1-out/CDCMilestone_Lcu.2RBY_BND_hq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCMilestone/CDCMilestone-allBND-lq.vcf > run1-out/CDCMilestone_Lcu.2RBY_BND_lq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCMilestone/CDCMilestone-allDEL-hq.vcf > run1-out/CDCMilestone_Lcu.2RBY_DEL_hq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCMilestone/CDCMilestone-allDEL-lq.vcf > run1-out/CDCMilestone_Lcu.2RBY_DEL_lq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCMilestone/CDCMilestone-allINS-hq.vcf > run1-out/CDCMilestone_Lcu.2RBY_INS_hq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCMilestone/CDCMilestone-allINS-lq.vcf > run1-out/CDCMilestone_Lcu.2RBY_INS_lq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCMilestone/CDCMilestone-allINV-hq.vcf > run1-out/CDCMilestone_Lcu.2RBY_INV_hq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCMilestone/CDCMilestone-allINV-lq.vcf > run1-out/CDCMilestone_Lcu.2RBY_INV_lq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCRobin/CDCRobin-allBND-hq.vcf > run1-out/CDCRobin_Lcu.2RBY_BND_hq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCRobin/CDCRobin-allBND-lq.vcf > run1-out/CDCRobin_Lcu.2RBY_BND_lq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCRobin/CDCRobin-allDEL-hq.vcf > run1-out/CDCRobin_Lcu.2RBY_DEL_hq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCRobin/CDCRobin-allDEL-lq.vcf > run1-out/CDCRobin_Lcu.2RBY_DEL_lq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCRobin/CDCRobin-allINS-hq.vcf > run1-out/CDCRobin_Lcu.2RBY_INS_hq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCRobin/CDCRobin-allINS-lq.vcf > run1-out/CDCRobin_Lcu.2RBY_INS_lq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCRobin/CDCRobin-allINV-hq.vcf > run1-out/CDCRobin_Lcu.2RBY_INV_hq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCRobin/CDCRobin-allINV-lq.vcf > run1-out/CDCRobin_Lcu.2RBY_INV_lq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCGreenstar/CDCGreenstar-allBND-hq.vcf > run1-out/CDCGreenstar_Lcu.2RBY_BND_hq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCGreenstar/CDCGreenstar-allBND-lq.vcf > run1-out/CDCGreenstar_Lcu.2RBY_BND_lq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCGreenstar/CDCGreenstar-allDEL-hq.vcf > run1-out/CDCGreenstar_Lcu.2RBY_DEL_hq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCGreenstar/CDCGreenstar-allDEL-lq.vcf > run1-out/CDCGreenstar_Lcu.2RBY_DEL_lq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCGreenstar/CDCGreenstar-allINS-hq.vcf > run1-out/CDCGreenstar_Lcu.2RBY_INS_hq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCGreenstar/CDCGreenstar-allINS-lq.vcf > run1-out/CDCGreenstar_Lcu.2RBY_INS_lq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCGreenstar/CDCGreenstar-allINV-hq.vcf > run1-out/CDCGreenstar_Lcu.2RBY_INV_hq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCGreenstar/CDCGreenstar-allINV-lq.vcf > run1-out/CDCGreenstar_Lcu.2RBY_INV_lq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCMaxim/CDCMaxim-allBND-hq.vcf > run1-out/CDCMaxim_Lcu.2RBY_BND_hq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCMaxim/CDCMaxim-allBND-lq.vcf > run1-out/CDCMaxim_Lcu.2RBY_BND_lq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCMaxim/CDCMaxim-allDEL-hq.vcf > run1-out/CDCMaxim_Lcu.2RBY_DEL_hq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCMaxim/CDCMaxim-allDEL-lq.vcf > run1-out/CDCMaxim_Lcu.2RBY_DEL_lq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCMaxim/CDCMaxim-allINS-hq.vcf > run1-out/CDCMaxim_Lcu.2RBY_INS_hq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCMaxim/CDCMaxim-allINS-lq.vcf > run1-out/CDCMaxim_Lcu.2RBY_INS_lq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCMaxim/CDCMaxim-allINV-hq.vcf > run1-out/CDCMaxim_Lcu.2RBY_INV_hq.vcf
python3 process-filtered-for-kp.py ../../SVIM-calls/svim-default-CDCMaxim/CDCMaxim-allINV-lq.vcf > run1-out/CDCMaxim_Lcu.2RBY_INV_lq.vcf
